### ISSUE TITLE
Links sind von normalem Text kaum zu unterscheiden

### ISSUE THREAD

**Issue by schauder** [cyberjug/website#11]
Man könnte Links grün machen? (Nur ein geschmackloser Vorschlag).

**Comment by feststelltaste** [comment]
Danke für den Hinweis! Ja, es ist echt hart so. Daher habe ich das angepasst:
![grafik](https://user-images.githubusercontent.com/1470822/76801066-326e3600-67d5-11ea-9bac-2e786a90c0cb.png)
